/* This file was generated by the Hex-Rays decompiler version 8.4.0.240320.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_1020();
void sub_1030();
void sub_1040();
void sub_1050();
void sub_1060();
void sub_1070();
void sub_1080();
void sub_1090();
void sub_10A0();
void sub_10B0();
void sub_10C0();
void sub_10D0();
void sub_10E0();
void sub_10F0();
void sub_1100();
// int __fastcall _cxa_finalize(void *);
// int putchar(int c);
// int *__errno_location(void);
// int puts(const char *s);
// ssize_t write(int fd, const void *buf, size_t n);
// int printf(const char *format, ...);
// void __noreturn __assert_fail(const char *assertion, const char *file, unsigned int line, const char *function);
// __uid_t geteuid(void);
// ssize_t read(int fd, void *buf, size_t nbytes);
// int memcmp(const void *s1, const void *s2, size_t n);
// int setvbuf(FILE *stream, char *buf, int modes, size_t n);
// int open(const char *file, int oflag, ...);
// void __noreturn exit(int status);
// char *strerror(int errnum);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void));
void *sub_1230();
__int64 sub_1260();
void *sub_12A0();
__int64 sub_12E0();
unsigned __int64 sub_12E9();
void fini(void); // idb
void term_proc();
// int __fastcall _libc_start_main(int (__fastcall *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int __fastcall __cxa_finalize(void *);
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN main;
_UNKNOWN init;
__int64 (__fastcall *off_3D50)() = &sub_12E0; // weak
__int64 (__fastcall *off_3D58)() = &sub_12A0; // weak
void *off_4008 = &off_4008; // idb
char aBsiza[6] = "bsiza"; // weak
_UNKNOWN unk_4018; // weak
FILE *stdout; // idb
FILE *stdin; // idb
char byte_4038; // weak


//----- (0000000000001000) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 40C8: using guessed type __int64 _gmon_start__(void);

//----- (0000000000001020) ----------------------------------------------------
void sub_1020()
{
  JUMPOUT(0LL);
}
// 1026: control flows out of bounds to 0

//----- (0000000000001030) ----------------------------------------------------
void sub_1030()
{
  sub_1020();
}

//----- (0000000000001040) ----------------------------------------------------
void sub_1040()
{
  sub_1020();
}

//----- (0000000000001050) ----------------------------------------------------
void sub_1050()
{
  sub_1020();
}

//----- (0000000000001060) ----------------------------------------------------
void sub_1060()
{
  sub_1020();
}

//----- (0000000000001070) ----------------------------------------------------
void sub_1070()
{
  sub_1020();
}

//----- (0000000000001080) ----------------------------------------------------
void sub_1080()
{
  sub_1020();
}

//----- (0000000000001090) ----------------------------------------------------
void sub_1090()
{
  sub_1020();
}

//----- (00000000000010A0) ----------------------------------------------------
void sub_10A0()
{
  sub_1020();
}

//----- (00000000000010B0) ----------------------------------------------------
void sub_10B0()
{
  sub_1020();
}

//----- (00000000000010C0) ----------------------------------------------------
void sub_10C0()
{
  sub_1020();
}

//----- (00000000000010D0) ----------------------------------------------------
void sub_10D0()
{
  sub_1020();
}

//----- (00000000000010E0) ----------------------------------------------------
void sub_10E0()
{
  sub_1020();
}

//----- (00000000000010F0) ----------------------------------------------------
void sub_10F0()
{
  sub_1020();
}

//----- (0000000000001100) ----------------------------------------------------
void sub_1100()
{
  sub_1020();
}

//----- (0000000000001200) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void))
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main((int (__fastcall *)(int, char **, char **))main, v4, &retaddr, (void (*)(void))init, fini, a3, &v5);
  __halt();
}
// 120A: positive sp value 8 has been found
// 1211: variable 'v3' is possibly undefined

//----- (0000000000001230) ----------------------------------------------------
void *sub_1230()
{
  return &unk_4018;
}

//----- (0000000000001260) ----------------------------------------------------
__int64 sub_1260()
{
  return 0LL;
}

//----- (00000000000012A0) ----------------------------------------------------
void *sub_12A0()
{
  void *result; // rax

  if ( !byte_4038 )
  {
    if ( &__cxa_finalize )
      _cxa_finalize(off_4008);
    result = sub_1230();
    byte_4038 = 1;
  }
  return result;
}
// 4038: using guessed type char byte_4038;

//----- (00000000000012E0) ----------------------------------------------------
// attributes: thunk
__int64 sub_12E0()
{
  return sub_1260();
}

//----- (00000000000012E9) ----------------------------------------------------
unsigned __int64 sub_12E9()
{
  int *v0; // rax
  char *v1; // rax
  int *v2; // rax
  char *v3; // rax
  int fd; // [rsp+8h] [rbp-118h]
  int v6; // [rsp+Ch] [rbp-114h]
  char buf[264]; // [rsp+10h] [rbp-110h] BYREF
  unsigned __int64 v8; // [rsp+118h] [rbp-8h]

  v8 = __readfsqword(0x28u);
  puts("You win! Here is your flag:");
  fd = open("/flag", 0);
  if ( fd >= 0 )
  {
    v6 = read(fd, buf, 0x100uLL);
    if ( v6 > 0 )
    {
      write(1, buf, v6);
      puts("\n");
    }
    else
    {
      v2 = __errno_location();
      v3 = strerror(*v2);
      printf("\n  ERROR: Failed to read the flag -- %s!\n", v3);
    }
  }
  else
  {
    v0 = __errno_location();
    v1 = strerror(*v0);
    printf("\n  ERROR: Failed to open the flag -- %s!\n", v1);
    if ( geteuid() )
    {
      puts("  Your effective user id is not 0!");
      puts("  You must directly run the suid binary in order to have the correct permissions!");
    }
  }
  return __readfsqword(0x28u) ^ v8;
}

//----- (0000000000001412) ----------------------------------------------------
void main(int a1, char **a2, char **a3)
{
  char v3; // [rsp+2Ah] [rbp-16h]
  int i; // [rsp+2Ch] [rbp-14h]
  int buf; // [rsp+32h] [rbp-Eh] BYREF
  __int16 v6; // [rsp+36h] [rbp-Ah]
  unsigned __int64 v7; // [rsp+38h] [rbp-8h]

  v7 = __readfsqword(0x28u);
  if ( a1 <= 0 )
    __assert_fail("argc > 0", "<stdin>", 0x32u, "main");
  puts("###");
  printf("### Welcome to %s!\n", *a2);
  puts("###");
  putchar(10);
  setvbuf(stdin, 0LL, 2, 0LL);
  setvbuf(stdout, 0LL, 2, 1uLL);
  puts(
    "This license verifier software will allow you to read the flag. However, before you can do so, you must verify that you");
  puts("are licensed to read flag files! This program consumes a license key over stdin. Each program may perform entirely");
  puts(
    "different operations on that input! You must figure out (by reverse engineering this program) what that license key is.");
  puts("Providing the correct license key will net you the flag!\n");
  buf = 0;
  v6 = 0;
  puts("Ready to receive your license key!\n");
  read(0, &buf, 5uLL);
  for ( i = 0; i <= 1; ++i )
  {
    v3 = *((_BYTE *)&buf + i);
    *((_BYTE *)&buf + i) = *((_BYTE *)&buf + 4 - i);
    *((_BYTE *)&buf + 4 - i) = v3;
  }
  puts("Checking the received license key!\n");
  if ( !memcmp(&buf, aBsiza, 5uLL) )
  {
    sub_12E9();
    exit(0);
  }
  puts("Wrong! No flag for you!");
  exit(1);
}

//----- (00000000000015E0) ----------------------------------------------------
void __fastcall init(unsigned int a1, __int64 a2, __int64 a3)
{
  signed __int64 v4; // rbp
  __int64 i; // rbx

  init_proc();
  v4 = &off_3D58 - &off_3D50;
  if ( v4 )
  {
    for ( i = 0LL; i != v4; ++i )
      ((void (__fastcall *)(_QWORD, __int64, __int64))*(&off_3D50 + i))(a1, a2, a3);
  }
}
// 3D50: using guessed type __int64 (__fastcall *off_3D50)();
// 3D58: using guessed type __int64 (__fastcall *off_3D58)();

//----- (0000000000001650) ----------------------------------------------------
void fini(void)
{
  ;
}

//----- (0000000000001658) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=58 queued=26 decompiled=26 lumina nreq=0 worse=0 better=0
// ALL OK, 26 function(s) have been successfully decompiled
